os: linux
language: go
install:
  - go get github.com/gohugoio/hugo

script:
  - hugo -d ../public
  
deploy:
  provider: pages
  cleanup: true
  token: $GITHUB_TOKEN
  local_dir: ../public
  target_branch: master
  repo: robcohen/robcohen.github.io
  on:
    branch: master