os: linux
language: shell
install:
  - curl -LO https://github.com/gohugoio/hugo/releases/download/v0.64.1/hugo_0.64.1_Linux-64bit.deb
  - sudo dpkg -i hugo_0.64.1_Linux-64bit.deb
  - rm hugo_0.64.1_Linux-64bit.deb

script:
  - hugo -d ../public
  
deploy:
  provider: pages
  cleanup: true
  token: $GITHUB_TOKEN
  local_dir: ../public
  target_branch: master
  repo: robcohen/robcohen.github.io
  on:
    branch: master