baseurl = "http://example.org/"
title = "Hugo Website"
theme = "hugo-theme-nix"
languageCode = "en-us"
disqusShortname = "your_disqus_shortname"

[menu]
  [[menu.header]]
    name = "post"
    weight = 0
    url = "/post"
  [[menu.header]]
    name = "about"
    weight = 1
    url = "/about"

[params]
  GithubID = "robcohen"
  TwitterID = "rob_cohen"
  LinkedInID = "rcohenme"
  Name = "Rob Cohen"
  HeaderUsername = "rob"
  HeaderHostname = "robcohen.dev"
  About = "Hack all the things."
  ProfilePicture = "/profile.jpg"
  Favicon = "/favicon.ico"

