baseurl = "https://www.rcohen.me"
title = "ROB COHEN"

theme = "coder"

languagecode = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[permalinks]
    posts = "posts/:title/"
    default = ":title/"

[params]
    author = "Rob Cohen"
    description = "Rob Cohen's Website"
    keywords = "blog,developer,personal"
    info = "Developer/Hacker"

[[params.social]]
    name = "Github"
    weight = 1
    url = "https://github.com/robcohen/"
[[params.social]]
    name = "Twitter"
    weight = 2
    url = "https://twitter.com/robcohen_me/"
[[params.social]]
    name = "LinkedIn"
    weight = 3
    url = "https://www.linkedin.com/in/rcohenme/"
[[params.social]]
    name = "Keybase"
    weight = 4
    url = "https://keybase.io/robertcohen"


[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/posts/"
[[menu.main]]
    name = "About"
    weight = 2
    url = "/about/"
