baseurl = "https://robcohen.dev"
title = "Rob Cohen"
theme = "hugo-theme-nix"
languageCode = "en-us"

[menu]
  [[menu.header]]
    name = "post"
    weight = 0
    url = "/posts"
  [[menu.header]]
    name = "about"
    weight = 1
    url = "/about"

[params]
  GithubID = "robcohen"
  GitlabID = "robcohen"
  TwitterID = "rob_cohen"
  LinkedInID = "rcohenme"
  Name = "Rob Cohen"
  HeaderUsername = "rob"
  HeaderHostname = "robcohen.dev"
  ProfilePicture = "/profile.gif"
  Favicon = "/favicon.ico"
  StackExchangeID = "your_stackexchange_id"
  StackOverflowID = "your_stackoverflow_id"
  Keybase = "robertcohen"
